/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   help_data2.c                                       :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: marvin <marvin@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/08/19 20:40:00 by marvin            #+#    #+#             */
/*   Updated: 2026/08/19 20:40:00 by marvin           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "help.h"

/* Second half of the help index: shell state, control flow, command
   resolution, history, tests -- and the SYNTAX topics.

   The syntax entries are the reason this is worth having at all. Knowing
   that `for` is a keyword does not tell you how to write one, and a shell
   whose help only covers its builtins teaches you half a language. */
static const t_help	g_help_2[] = {
{"set", "shell",
	"set [-abefhkmnptuvxCH] [-o opt] [--] [arg ...]",
	"set shell options and positional parameters"},
{"compgen", "shell",
	"compgen [-abcdfkv] [-A action] [-W wordlist] [word]",
	"print the completions the shell would offer for word"},
{"complete", "shell",
	"complete [-abcdfkv] [-A action] [-W list] [-F fn] [-pr] name ...",
	"register what to offer when completing an argument of name"},
{"shopt", "shell",
	"shopt [-pqsu] [-o] [optname ...]",
	"toggle the extra (non-POSIX) shell options"},
{"exit", "shell",
	"exit [n]",
	"leave the shell with status n"},
{"exec", "shell",
	"exec [command [arg ...]] [redirection ...]",
	"replace the shell, or apply redirections to it"},
{"eval", "shell",
	"eval [arg ...]",
	"join the arguments and run them as a command"},
{".", "shell",
	". filename [arguments]",
	"read and run a file in the current shell"},
{"source", "shell",
	"source filename [arguments]",
	"same as ."},
{"times", "shell",
	"times",
	"print user and system time for the shell"},
{"trap", "shell",
	"trap [-lp] [[action] signal ...]",
	"run an action on a signal or on EXIT"},
{"umask", "shell",
	"umask [-S] [-p] [mode]",
	"show or set the file-creation mask"},
{"update", "shell",
	"update [--now|--check|--version]",
	"check for a newer hellish and install it"},
{"help", "shell",
	"help [-s] [topic ...]",
	"this. `help NAME` explains one topic"},
{"break", "control",
	"break [n]",
	"leave a for/while/until loop"},
{"continue", "control",
	"continue [n]",
	"start the next turn of a loop"},
{"return", "control",
	"return [n]",
	"return from a function or a sourced file"},
{"shift", "control",
	"shift [n]",
	"drop the first n positional parameters"},
{"command", "commands",
	"command [-pVv] name [arg ...]",
	"run a command, ignoring functions and aliases"},
{"builtin", "commands",
	"builtin [name [args ...]]",
	"run a shell builtin, bypassing function lookup"},
{"type", "commands",
	"type [-afptP] name [name ...]",
	"say how a name would be resolved"},
{"hash", "commands",
	"hash [-lr] [-p path] [-dt] [name ...]",
	"show or change the remembered command paths"},
{"alias", "commands",
	"alias [-p] [name[=value] ...]",
	"define or list command aliases"},
{"unalias", "commands",
	"unalias [-a] name [name ...]",
	"remove aliases"},
{"history", "history",
	"history [-c] [-d n] [n] | history -anrw [file]",
	"show or edit the command history"},
{"pretty", "shell",
	"pretty [-p] | list | on NAME... | off NAME... | mode NAME",
	"named presets for the shell's behaviour knobs"},
{"fc", "history",
	"fc [-e ed] [-lnr] [first] [last] | fc -s [pat=rep]",
	"re-edit and re-run past commands"},
{"test", "tests",
	"test expr | [ expr ]",
	"evaluate a conditional expression"},
{"[", "tests",
	"[ expr ]",
	"same as test; the closing ] is required"},
{"[[", "tests",
	"[[ expr ]]",
	"conditional with pattern and regex matching"},
{"true", "tests",
	"true",
	"do nothing, successfully"},
{"false", "tests",
	"false",
	"do nothing, unsuccessfully"},
{":", "tests",
	":",
	"do nothing; the classic no-op"},
{"ulimit", "shell",
	"ulimit [-SHabcdefiklmnpqrstuvxPT] [limit]",
	"show or set process resource limits"},
{"for", "syntax",
	"for NAME [in WORD ...]; do LIST; done",
	"loop over words"},
{"for((", "syntax",
	"for ((exp1; exp2; exp3)); do LIST; done",
	"C-style counting loop"},
{"while", "syntax",
	"while LIST; do LIST; done",
	"loop while a list succeeds"},
{"until", "syntax",
	"until LIST; do LIST; done",
	"loop until a list succeeds"},
{"if", "syntax",
	"if LIST; then LIST; [elif ...] [else LIST] fi",
	"branch on a command's exit status"},
{"case", "syntax",
	"case WORD in PATTERN) LIST ;; ... esac",
	"branch on a pattern match"},
{"function", "syntax",
	"name () { LIST; } | function name { LIST; }",
	"define a function"},
{"((", "syntax",
	"(( expression ))",
	"arithmetic; status 0 when the value is non-zero"},
{"$((", "syntax",
	"$(( expression ))",
	"substitute the value of an arithmetic expression"},
{"$(", "syntax",
	"$( LIST )  or  `LIST`",
	"substitute a command's output"},
{"redirection", "syntax",
	"> < >> 2>&1 <<EOF <<<word /dev/tcp/host/port",
	"send a command's input and output elsewhere"},
{"pipeline", "syntax",
	"cmd1 | cmd2   [!] cmd1 |& cmd2",
	"feed one command's output into the next"},
{"setopt", "zsh",
	"setopt [name ...]",
	"turn on zsh-named shell options"},
{"unsetopt", "zsh",
	"unsetopt [name ...]",
	"turn off zsh-named shell options"},
{"emulate", "zsh",
	"emulate [-L] {zsh|sh|ksh|bash}",
	"switch dialect; in a function it reverts on return"},
{"print", "zsh",
	"print [-nrlP] [--] [arg ...]",
	"zsh's echo: escapes on by default, -r turns them off"},
{"autoload", "zsh",
	"autoload [-Uz] name ...",
	"define a function from a file on $fpath"},
{"zmodload", "zsh",
	"zmodload [args ...]",
	"not supported: hellish has no loadable modules"},
{"zstyle", "zsh",
	"zstyle [pattern style value ...]",
	"vcs_info formats/actionformats are honoured; the rest is stubbed"},
{"colors", "zsh",
	"colors",
	"define $fg[..] $bg[..] $fg_bold[..] $reset_color like zsh's colors"},
{"vcs_info", "zsh",
	"vcs_info",
	"fill $vcs_info_msg_0_ with the git branch, zstyle formats honoured"},
{"compdef", "zsh",
	"compdef [args ...]",
	"not supported: hellish has no zsh completion system"},
{"zle", "zsh",
	"zle -N widget [fn] | zle widget",
	"register a line-editor widget; key dispatch is not wired yet"},
{"bindkey", "zsh",
	"bindkey [-M keymap] seq widget",
	"record a key binding for a zle widget"},
{"add-zsh-hook", "zsh",
	"add-zsh-hook hook function",
	"run a function on an event; only chpwd fires here"},
{"is-at-least", "zsh",
	"is-at-least need [have]",
	"0 when version have (default $ZSH_VERSION) is need or newer"},
{NULL, NULL, NULL, NULL}
};

/* The second half of the index. */
const t_help	*help_index2(void)
{
	return (g_help_2);
}
