#!/usr/bin/env python3
"""Turn the hyperfine JSON exports in bench/.artifacts/perf/ into
bench/results.md: one table per dimension with median, stddev, coefficient
of variation (flagged when > 3%), and speedup relative to dash and bash.
"""
import json
import os
import platform

BENCH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ART = os.path.join(BENCH, '.artifacts', 'perf')
OUT = os.path.join(BENCH, 'results.md')

DIMENSIONS = [
    ('Startup', 'A shell is born, runs `true`, exits.', ['startup']),
    ('Parser throughput', '50k lines of realistic code under `set -n` — '
     'parse everything, execute nothing.', ['parse50k']),
    ('Loop / builtin throughput', '100k-iteration `while` loops: POSIX '
     'arithmetic, string concat, the `:` builtin, `read` over a 100k-line '
     'file.', ['loop_arith', 'loop_concat', 'loop_colon', 'loop_read']),
    ('Fork workloads', '1k iterations: `$(true)` (hellish takes its '
     'forkless fast path — the ksh93 trick; bash/dash fork), '
     '`$(/bin/true)` (everyone forks+execs), and a 3-stage pipeline.',
     ['fork_cmdsub', 'fork_cmdsub_ext', 'fork_pipeline']),
    ('Real workload: autoconf', 'GNU hello 2.12.1 `./configure` with '
     'CONFIG_SHELL pointed at each shell.', ['configure']),
]

CV_LIMIT = 0.03


def load(name):
    """hyperfine -n <label> exports the label as the `command` field."""
    path = os.path.join(ART, name + '.json')
    if not os.path.exists(path):
        return None
    with open(path) as f:
        data = json.load(f)
    return {r['command']: r for r in data['results']}


def fmt_time(sec):
    if sec < 1.0:
        return '%.2f ms' % (sec * 1000)
    return '%.3f s' % sec


def main():
    gov = os.environ.get('GOVERNOR', 'unknown')
    lines = []
    a = lines.append
    a('# Benchmark results: hellish vs bash vs dash')
    a('')
    a('Generated by `make perf`.  Methodology and every fairness choice: '
      '[METHODOLOGY.md](METHODOLOGY.md).')
    a('')
    a('Environment: %s, CPU governor `%s`%s.' % (
        platform.platform(), gov,
        '' if gov == 'performance' else
        ' ⚠ **not** `performance` — absolute numbers are pessimistic and '
        'noisier; the CV column is the reliability signal'))
    a('')
    a('Speedup columns: that shell\'s median divided into the reference '
      'shell\'s median — `2.0×` means twice as fast as the reference. '
      'CV = stddev/median; results with CV > 3% are flagged ⚠ unreliable.')
    a('')
    for title, blurb, names in DIMENSIONS:
        rows = [(n, load(n)) for n in names]
        rows = [(n, r) for n, r in rows if r]
        if not rows:
            continue
        a('## %s' % title)
        a('')
        a(blurb)
        a('')
        a('| benchmark | shell | median | stddev | CV | vs dash | vs bash |')
        a('|---|---|---|---|---|---|---|')
        for name, labeled in rows:
            med = {l: labeled[l]['median'] for l in labeled}
            for label in ('hellish', 'bash', 'dash'):
                if label not in labeled:
                    continue
                r = labeled[label]
                cv = r['stddev'] / r['median'] if r['median'] else 0.0
                flag = ' ⚠' if cv > CV_LIMIT else ''
                vs_dash = ('%.2f×' % (med['dash'] / r['median'])
                           if 'dash' in med else '—')
                vs_bash = ('%.2f×' % (med['bash'] / r['median'])
                           if 'bash' in med else '—')
                a('| %s | %s | %s | %s | %.1f%%%s | %s | %s |' % (
                    name, '**hellish**' if label == 'hellish' else label,
                    fmt_time(r['median']), fmt_time(r['stddev']),
                    cv * 100, flag, vs_dash, vs_bash))
        a('')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print('wrote %s' % OUT)


if __name__ == '__main__':
    main()
